FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build

COPY ["*PaymentGateway.API.csproj", "src/PaymentGateway.API/"]
COPY ["*PaymentGateway.Domain.csproj", "src/PaymentGateway.Domain/"]
COPY ["*PaymentGateway.Model.csproj", "src/PaymentGateway.Model/"]
COPY ["*PaymentGateway.Data.csproj", "src/PaymentGateway.Data/"]

RUN dotnet restore "src/PaymentGateway.API/PaymentGateway.API.csproj"
COPY . .
WORKDIR "/src/src/PaymentGateway.API"
RUN dotnet build "PaymentGateway.API.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "PaymentGateway.API.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "PaymentGateway.API.dll"]
